<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Follower_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get follower by id
     */
    function get_follower($id)
    {
        return $this->db->get_where('followers',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all followers count
     */
    function get_all_followers_count()
    {
        $this->db->from('followers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all followers
     */
    function get_all_followers($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('followers')->result_array();
    }
        
    /*
     * function to add new follower
     */
    function add_follower($params)
    {
        $this->db->insert('followers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update follower
     */
    function update_follower($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('followers',$params);
    }
    
    /*
     * function to delete follower
     */
    function delete_follower($id)
    {
        return $this->db->delete('followers',array('id'=>$id));
    }
}
