<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vote_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vote_type by id
     */
    function get_vote_type($id)
    {
        return $this->db->get_where('vote_types',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all vote_types count
     */
    function get_all_vote_types_count()
    {
        $this->db->from('vote_types');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vote_types
     */
    function get_all_vote_types($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
            if(!empty($params['search_val'])){
				$this->db->like('name',$params['search_val']);
			}
        }
        return $this->db->get('vote_types')->result_array();
    }
        
    /*
     * function to add new vote_type
     */
    function add_vote_type($params)
    {
        $this->db->insert('vote_types',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vote_type
     */
    function update_vote_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vote_types',$params);
    }
    
    /*
     * function to delete vote_type
     */
    function delete_vote_type($id)
    {
        return $this->db->delete('vote_types',array('id'=>$id));
    }
}
