<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Report_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Report_user_model');
    } 

    /*
     * Listing of report_user
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('report_user/index?');
        $config['total_rows'] = $this->Report_user_model->get_all_report_user_count();
        $this->pagination->initialize($config);

        $data['report_user'] = $this->Report_user_model->get_all_report_user($params);
        
        $data['_view'] = 'report_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new report_user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('user_id','User Id','required|integer');
		$this->form_validation->set_rules('report_user_id','Report User Id','required|integer');
		$this->form_validation->set_rules('cdate','Cdate','required');
		$this->form_validation->set_rules('mdate','Mdate','required');
		$this->form_validation->set_rules('report_text','Report Text','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'report_user_id' => $this->input->post('report_user_id'),
				'cdate' => $this->input->post('cdate'),
				'mdate' => $this->input->post('mdate'),
				'report_text' => $this->input->post('report_text'),
            );
            
            $report_user_id = $this->Report_user_model->add_report_user($params);
            redirect('report_user/index');
        }
        else
        {            
            $data['_view'] = 'report_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a report_user
     */
    function edit($id)
    {   
        // check if the report_user exists before trying to edit it
        $data['report_user'] = $this->Report_user_model->get_report_user($id);
        
        if(isset($data['report_user']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('user_id','User Id','required|integer');
			$this->form_validation->set_rules('report_user_id','Report User Id','required|integer');
			$this->form_validation->set_rules('cdate','Cdate','required');
			$this->form_validation->set_rules('mdate','Mdate','required');
			$this->form_validation->set_rules('report_text','Report Text','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'report_user_id' => $this->input->post('report_user_id'),
					'cdate' => $this->input->post('cdate'),
					'mdate' => $this->input->post('mdate'),
					'report_text' => $this->input->post('report_text'),
                );

                $this->Report_user_model->update_report_user($id,$params);            
                redirect('report_user/index');
            }
            else
            {
                $data['_view'] = 'report_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The report_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting report_user
     */
    function remove($id)
    {
        $report_user = $this->Report_user_model->get_report_user($id);

        // check if the report_user exists before trying to delete it
        if(isset($report_user['id']))
        {
            $this->Report_user_model->delete_report_user($id);
            redirect('report_user/index');
        }
        else
            show_error('The report_user you are trying to delete does not exist.');
    }
    
}
